### ISSUE TITLE
Error upon Running Minidot

### ISSUE THREAD

**Issue by Jome0169** [thackl/minidot#10]
Hello, I recently discovered minidot, and it seems like a very useful program. I am snagging an issue however. Whenever I run it I get the following error.

``` 
Loading required package: proto
[12:43:19] /home/pabster212/data/Programs/minimap2/minimap2 .. ok
[12:43:19] samtools .. ok
[12:43:19] prepping .. done
[12:45:00] mode: fast (2242694751 bp) "-L 500 -c 15"
[12:45:00] mapping .. failed
[ERROR] failed to open file '500'
[ERROR] failed to open file '500'
```

Any idea what this error could be? The command executed was `~/data/Programs/minidot/bin/minidot -M ~/data/Programs/minimap2/minimap2 -o test222.pdf A10.spades.contigs.fa ref.fa` .

**Comment by iimog** [comment]
Hi @Jome0169 I came across a similar problem. I see that you are using `minimap2` (not `minimap` - which is no longer developed). However, the default parameters added to the call to `minimap` by `minidot` internally (`-L 500 -c 15`) do not make sense for `minimap2`, `-L` has a totally different meaning now and does not take an argument. That is why `minimap2` considers the 500 as a file name. So I see two possible solutions:
1. Use `minimap`
2. Use the `-m` option to provide parameters that work with `minimap2`

**Comment by thackl** [comment]
@iimog is right. minidot works with `minimap`, not `minimap2`. I haven't had the time yet to port it... It should however, be possible to use the `-m` parameter to manually specify your minimap2 optionsand overwrite minidot's defaults, which don't make sense with minimap2 ...
